version: '3'

services:

  git-server:
    image: deekue/docker-git-server:latest
    build: .
    restart: unless-stopped
    container_name: git-server
    ports:
      - ${SERVER_PORT:-2222}:22
    volumes:
      - ${DATA_PATH:-~/git-server}/keys:/etc/ssh/keys:ro
      - ${DATA_PATH:-~/git-server}/host-keys:/etc/ssh/host-keys
      - ${DATA_PATH:-~/git-server}/repos:/git:ro
    environment:
      - SSHD_DEBUG=${SSHD_DEBUG:-false}  # set to true for debug output
   

