version: '2'

services:

  git-server:
    image: deekue/docker-git-server:localbuild
    build: .
    restart: unless-stopped
    container_name: git-server
    ports:
      - "127.0.0.1:2222:22"
    volumes:
      - ~/git-server/keys:/etc/ssh/keys:ro
      - ~/git-server/host-keys:/etc/ssh/host-keys
      - ~/git-server/repos:/git:ro
    environment:
      - SSHD_DEBUG=false  # set to true for debug output
   

